### ISSUE TITLE
Add SEIRD model with waning immunity

### ISSUE THREAD

**Issue by ben18785** [Como-DTC-Collaboration/como-models#14]
@DSeiferth and @hfldai pointed me to the Como package where they allow recovered individuals to become susceptible again. In the meeting, we decided to implement a basic SEIRD model where R -> S at a certain rate. We think this'll result in an endemic equilibrium and (possibly) a number of epidemic waves.

**Comment by hfldai** [comment]
Here's the example plot showing the effects when including R -> S:
* R -> S, transmission rate = 0.01
![SEIaImIsRD_omega-0 01](https://user-images.githubusercontent.com/44946606/116530992-9323d980-a8d6-11eb-90a2-c94dd2fca54a.png)
* No transmission from R -> S
![SEIaImIsRD_omega-0](https://user-images.githubusercontent.com/44946606/116531278-e8f88180-a8d6-11eb-8a93-26faecee5da2.png)

**Comment by ben18785** [comment]
Ha! That's really interesting. And, I guess, makes sense in terms of
oscillatory behaviour since S -> I (and a reduction in S) then, later, I ->
R -> S (leading to an increase).

**Comment by ben18785** [comment]
This is in there via #53
