### ISSUE TITLE
Rural vs. urban populations

### ISSUE THREAD

**Issue by solveigvandervegt** [Como-DTC-Collaboration/como-models#16]
As the rate of contact and therefor the rate of infection will be quite different between rural and urban communities, it is relevant to include this in the model. The first task will be to figure out what the best approach is to modeling these different communities and how they interact, and the second will be to add in age-structure as we now have contact matrices for rural and urban populations.

**Comment by ben18785** [comment]
This was addressed much earlier (not sure when!).
