### ISSUE TITLE
Moving all Generics into generics.R after merging branches

### ISSUE THREAD

**Issue by hfldai** [Como-DTC-Collaboration/como-models#21]
As pointed in the answer to @I-Bouros 's [stackoverflow question](https://stackoverflow.com/questions/68113799/how-can-you-create-multiple-s4-classes-with-similarly-named-methods-in-r), duplicated declarations of generics are not allowed in R. To avoid ambiguity structurally, after merging the model branches we can 
1. move all generics declarations (`setGeneric.(..)`) into `generics.R`,
2. add `#' @include generics.R` to the front of each model R file, and `setMethod` can be used as usual.

An extra step might be documenting all shared generics into the same .Rd file in man (e.g. `generics.Rd`), while keeping class-specific generics in their class-specific Rd files.

**Comment by solveigvandervegt** [comment]
We also need to change the documentation of the generics function so they apply to all models. Currently the documentation for the generics refers to the basic SEIRD model specifically.

**Comment by ben18785** [comment]
Merged by #37
