### ISSUE TITLE
Whether to include the output of R0() and run() as incidences of the classes

### ISSUE THREAD

**Issue by hfldai** [Como-DTC-Collaboration/como-models#31]
In development, methods or functionalities written for S4 classes often return an object of the corresponding S4 class, and add/update the corresponding incidences into the object accordingly. In this way, one can access the computed values within the object by e.g. `object@value`. In our classes, we already have methods like `initial_conditions<-` and `transmission_parameters<-` working in this way.

Shall we do the same for the `R0()` and `run()` methods? Currently they return a value and a list, respectively. In other words, would we want to include the simulation output and R0 value as incidences of our classes?

**Comment by ben18785** [comment]
Decided to stay with R0 as returning a value since it's easier for users.
