### ISSUE TITLE
Use pkgdown to make a website for the package

### ISSUE THREAD

**Issue by ben18785** [Como-DTC-Collaboration/como-models#61]
[This](https://github.com/r-lib/pkgdown) seems to suggest that we can produce static HTML versions of our vignettes.

**Comment by hfldai** [comment]
@ben18785 [This](https://sahirbhatnagar.com/blog/2020/03/03/creating-a-website-for-your-r-package/) suggests we can use `pkgdown::build_site()` and easy manual set up in [Settings] to create the HTML github pages on the generated /doc folder. It requires manual update for docs/ whenever we have a local change, but much easier than the heavy setups in using `usethis::use_pkgdown_github_pages()` for automatically documentation. Only thing is that the access to [Settings] seems to be restricted to the owners of the repo.

**Comment by ben18785** [comment]
Closed by #62
