### ISSUE TITLE
Change package authors

### ISSUE THREAD

**Issue by ben18785** [Como-DTC-Collaboration/como-models#63]
At the moment, the package has @sumalibajaj and @fcooper8472 as its authors in the `DESCRIPTION` file. I'd propose we change this to "The Como-DTC Development Team" and use the group email that was setup for the Shiny App.

**Comment by fcooper8472** [comment]
Yep, purely legacy from when we initially created the project. Completely agree with your suggestions @ben18785

**Comment by ben18785** [comment]
Closed by #66
